version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
    networks:
      - mynetwork

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: banco_de_contatos
      MYSQL_USER: bdc
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork: